data:
  bbox_margin: 20
  colormode: RGB
  inference:
    normalize_images: true
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling:
      - 0.5
      - 1.25
      translation: 0
    crop_sampling:
      width: 448
      height: 448
      max_shift: 0.1
      method: hybrid
    gaussian_noise: 12.75
    motion_blur: true
    normalize_images: true
device: mps
metadata:
  project_path: 
    /Users/artjom/git/entrance-observer-pose-deeplabcut/GratheonBeePose-tot_ra-2025-09-13
  pose_config_path: 
    /Users/artjom/git/entrance-observer-pose-deeplabcut/GratheonBeePose-tot_ra-2025-09-13/dlc-models-pytorch/iteration-0/GratheonBeePoseSep13-trainset95shuffle2/train/pytorch_config.yaml
  bodyparts:
  - head
  - thorax
  - abdomen
  - antenna-left
  - antenna-right
  - fore-leg-left
  - fore-leg-right
  - mid-leg-left
  - mid-leg-right
  - hind-leg-left
  - hind-leg-right
  - wing-left
  - wing-right
  unique_bodyparts: []
  individuals:
  - individual1
  - individual2
  - individual3
  - individual4
  - individual5
  - individual6
  - individual7
  - individual8
  - individual9
  - individual10
  with_identity: false
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: false
    freeze_bn_weights: false
    pretrained: false
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: DLCRNetHead
      predictor:
        type: PartAffinityFieldPredictor
        num_animals: 10
        num_multibodyparts: 13
        num_uniquebodyparts: 0
        nms_radius: 5
        sigma: 1.0
        locref_stdev: 7.2801
        min_affinity: 0.05
        graph: &id001
        - - 0
          - 1
        - - 0
          - 2
        - - 0
          - 3
        - - 0
          - 4
        - - 0
          - 5
        - - 0
          - 6
        - - 0
          - 7
        - - 0
          - 8
        - - 0
          - 9
        - - 0
          - 10
        - - 0
          - 11
        - - 0
          - 12
        - - 1
          - 2
        - - 1
          - 3
        - - 1
          - 4
        - - 1
          - 5
        - - 1
          - 6
        - - 1
          - 7
        - - 1
          - 8
        - - 1
          - 9
        - - 1
          - 10
        - - 1
          - 11
        - - 1
          - 12
        - - 2
          - 3
        - - 2
          - 4
        - - 2
          - 5
        - - 2
          - 6
        - - 2
          - 7
        - - 2
          - 8
        - - 2
          - 9
        - - 2
          - 10
        - - 2
          - 11
        - - 2
          - 12
        - - 3
          - 4
        - - 3
          - 5
        - - 3
          - 6
        - - 3
          - 7
        - - 3
          - 8
        - - 3
          - 9
        - - 3
          - 10
        - - 3
          - 11
        - - 3
          - 12
        - - 4
          - 5
        - - 4
          - 6
        - - 4
          - 7
        - - 4
          - 8
        - - 4
          - 9
        - - 4
          - 10
        - - 4
          - 11
        - - 4
          - 12
        - - 5
          - 6
        - - 5
          - 7
        - - 5
          - 8
        - - 5
          - 9
        - - 5
          - 10
        - - 5
          - 11
        - - 5
          - 12
        - - 6
          - 7
        - - 6
          - 8
        - - 6
          - 9
        - - 6
          - 10
        - - 6
          - 11
        - - 6
          - 12
        - - 7
          - 8
        - - 7
          - 9
        - - 7
          - 10
        - - 7
          - 11
        - - 7
          - 12
        - - 8
          - 9
        - - 8
          - 10
        - - 8
          - 11
        - - 8
          - 12
        - - 9
          - 10
        - - 9
          - 11
        - - 9
          - 12
        - - 10
          - 11
        - - 10
          - 12
        - - 11
          - 12
        edges_to_keep:
        - 13
        - 12
        - 33
        - 0
        - 50
        - 46
        - 41
        - 44
        - 65
        - 7
        - 57
        - 77
        - 23
        - 14
        - 1
        - 24
        - 45
        - 9
        - 39
        - 60
        - 42
        - 25
        - 37
        - 5
        - 38
        - 26
        - 3
        - 2
        - 4
        - 6
        - 47
        - 74
        - 35
        - 52
        - 27
        - 8
        - 11
        - 19
        - 10
        - 15
        - 30
        - 16
        - 36
        - 59
        - 62
        - 61
        - 72
        - 58
        - 28
        - 54
        - 18
        - 49
        - 43
        - 69
        - 53
        - 29
        - 75
        - 56
        - 70
        - 51
        - 68
        - 67
        - 21
        apply_sigmoid: true
        clip_scores: false
      target_generator:
        type: SequentialGenerator
        generators:
        - type: HeatmapPlateauGenerator
          num_heatmaps: 13
          pos_dist_thresh: 17
          heatmap_mode: KEYPOINT
          gradient_masking: false
          generate_locref: true
          locref_std: 7.2801
        - type: PartAffinityFieldGenerator
          graph: *id001
          width: 20
      criterion:
        heatmap:
          type: WeightedBCECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
        paf:
          type: WeightedHuberCriterion
          weight: 0.1
      heatmap_config:
        channels:
        - 2048
        - 13
        kernel_size:
        - 3
        strides:
        - 2
      locref_config:
        channels:
        - 2048
        - 26
        kernel_size:
        - 3
        strides:
        - 2
      paf_config:
        channels:
        - 2048
        - 156
        kernel_size:
        - 3
        strides:
        - 2
      num_stages: 5
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus:
  key_metric: test.mAP
  key_metric_asc: true
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0005
  scheduler:
    type: LRListScheduler
    params:
      lr_list:
      - - 0.0001
      - - 1e-05
      milestones:
      - 90
      - 120
  snapshots:
    max_snapshots: 5
    save_epochs: 50
    save_optimizer_state: false
train_settings:
  batch_size: 8
  dataloader_workers: 0
  dataloader_pin_memory: false
  display_iters: 1000
  epochs: 200
  seed: 42
